import { useRef, useState, type FormEvent } from 'react'
import { changePassword } from '../api/authentication'

export function PasswordChangePage({ onComplete, onCancel }: { onComplete: () => void; onCancel: () => void }) {
  const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState<string | null>(null)
  const currentRef = useRef<HTMLInputElement>(null)
  function showError(message: string) { setCurrent(''); setNext(''); setConfirmation(''); setError(message); queueMicrotask(() => currentRef.current?.focus()) }
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); if (next !== confirmation) { showError('Die Passwörter stimmen nicht überein.'); return } try { await changePassword(current, next); setCurrent(''); setNext(''); setConfirmation(''); onComplete() } catch { showError('Das Passwort konnte nicht geändert werden. Prüfen Sie Ihre Angaben.') } }
  return <main className="auth-layout"><section className="auth-card"><h1>Passwort ändern</h1>{error && <p id="password-change-error" role="alert" className="auth-message">{error}</p>}<form onSubmit={(event) => void submit(event)}><label>Aktuelles Passwort<input ref={currentRef} required type="password" autoComplete="current-password" aria-invalid={!!error} aria-describedby={error ? 'password-change-error' : undefined} value={current} onChange={(event) => setCurrent(event.target.value)} /></label><label>Neues Passwort<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" aria-invalid={!!error} aria-describedby={error ? 'password-change-error' : undefined} value={next} onChange={(event) => setNext(event.target.value)} /></label><label>Passwort bestätigen<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" aria-invalid={!!error} aria-describedby={error ? 'password-change-error' : undefined} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><div className="auth-actions"><button type="button" onClick={onCancel}>Abbrechen</button><button type="submit">Passwort ändern</button></div></form></section></main>
}
