import type { TerminologyCatalog } from '../config/terminology'

export const terminologyDefaults: TerminologyCatalog = {
  'course.singular': 'Lehrveranstaltung',
  'course.plural': 'Lehrveranstaltungen',
  'course.navigation': 'Lehrveranstaltungen',
  'course.heading': 'Lehrveranstaltungen',
  'course.fieldLabel': 'Lehrveranstaltung',
  'course.tableHeading': 'Lehrveranstaltung',
  'lecturer.singular': 'Lehrende Person',
  'lecturer.plural': 'Lehrende',
  'lecturer.navigation': 'Lehrende',
  'lecturer.heading': 'Lehrende',
  'lecturer.fieldLabel': 'Lehrende Person',
  'lecturer.tableHeading': 'Lehrende Person',
  'cohort.singular': 'Kohorte',
  'cohort.plural': 'Kohorten',
  'cohort.navigation': 'Kohorten',
  'cohort.heading': 'Kohorten',
  'cohort.fieldLabel': 'Kohorte',
  'cohort.tableHeading': 'Kohorte',
  'room.singular': 'Raum',
  'room.plural': 'Räume',
  'room.navigation': 'Räume',
  'room.heading': 'Räume',
  'room.fieldLabel': 'Raum',
  'room.tableHeading': 'Raum',
  'schedule.navigation': 'Planung',
  'schedule.heading': 'Terminplanung',
  'academicData.navigation': 'Stammdaten',
  'academicData.heading': 'Akademische Stammdaten',
}
