import { useState } from 'react'
import type { CreateManualExamRequest, ExamConfiguration, ExamSession, UpdateExamRequest } from '../api/examScheduling'

type Option = { id: number; name: string; capacity?: number }
export function ExamManualSessionEditor({ mode, configuration, exam, snapshotToken, semesterId, lecturers, rooms, busy, serverError, onCancel, onSubmit }: { mode: 'create' | 'edit'; configuration?: ExamConfiguration; exam?: ExamSession; snapshotToken: string; semesterId: number; lecturers: Option[]; rooms: Option[]; busy: boolean; serverError?: string; onCancel: () => void; onSubmit: (request: CreateManualExamRequest | UpdateExamRequest) => Promise<void> }) {
  const [day, setDay] = useState(exam?.date ?? '')
  const [startTime, setStartTime] = useState(exam?.startTime ?? '09:00')
  const [lecturerId, setLecturerId] = useState(exam?.lecturer.id ?? configuration?.responsibleLecturerId ?? lecturers[0]?.id ?? 0)
  const [roomId, setRoomId] = useState(exam?.room.id ?? rooms[0]?.id ?? 0)
  const [error, setError] = useState('')
  const retainedDuration = mode === 'edit' && exam ? exam.durationMinutes : configuration?.durationMinutes
  async function submit() { if (!day || !startTime || !lecturerId || !roomId || (mode === 'create' && !configuration)) { setError('Complete every placement field.'); return } setError(''); if (mode === 'create') await onSubmit({ semesterId, date: day, startTime, lecturerId, roomId, expectedConfigurationRevision: configuration!.revision, inputSnapshotToken: snapshotToken }); else await onSubmit({ date: day, startTime, lecturerId, roomId, expectedExamRevision: exam!.revision, inputSnapshotToken: snapshotToken }) }
  return <section className="exam-manual-editor" aria-labelledby="exam-manual-title"><h3 id="exam-manual-title">{mode === 'create' ? 'Place exam manually' : `Correct ${exam?.lifecycleStatus} exam`}</h3><p className="constraint-note">Duration is fixed at {retainedDuration} minutes. Any start time is allowed when all hard constraints pass; the recommended range remains optional.</p><div className="exam-form-grid"><label className="constraint-field"><span>Date</span><input type="date" value={day} disabled={busy} onChange={(event)=>setDay(event.target.value)}/></label><label className="constraint-field"><span>Start time</span><input type="time" value={startTime} disabled={busy} onChange={(event)=>setStartTime(event.target.value)}/></label><label className="constraint-field"><span>Lecturer</span><select value={lecturerId} disabled={busy} onChange={(event)=>setLecturerId(Number(event.target.value))}>{lecturers.map((option)=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label className="constraint-field"><span>Room</span><select value={roomId} disabled={busy} onChange={(event)=>setRoomId(Number(event.target.value))}>{rooms.map((option)=><option key={option.id} value={option.id}>{option.name}{option.capacity ? ` (${option.capacity})` : ''}</option>)}</select></label></div>{(error || serverError)&&<div role="alert" className="alert-item">{[error, serverError].filter(Boolean).join(' ')}</div>}<div className="dialog-actions"><button type="button" className="secondary-button" disabled={busy} onClick={onCancel}>Cancel</button><button type="button" disabled={busy} onClick={()=>void submit()}>{busy?'Saving…':'Save exam placement'}</button></div></section>
}
