import { useMemo, useState } from 'react'
import { generateExams, prepareExamGeneration, type ExamCoursePlanningState, type ExamGenerationPreparation, type ExamGenerationResult, type ExamSchedulingApiError } from '../api/examScheduling'
import { ExamGenerationResultSummary } from './ExamGenerationResultSummary'

export function ExamGenerationPanel({ semesterId, courses, disabled, onChanged }: { semesterId: number; courses: ExamCoursePlanningState[]; disabled: boolean; onChanged: (result: ExamGenerationResult) => Promise<void> | void }) {
  const [selected, setSelected] = useState<number[]>([])
  const [preparation, setPreparation] = useState<ExamGenerationPreparation | null>(null)
  const [result, setResult] = useState<ExamGenerationResult | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const selectableCourseIds = useMemo(() => new Set(courses.filter((course) => !['DISABLED', 'ACTIVE_EXAM_EXISTS'].includes(course.generationEligibility.code ?? '')).map((course) => course.courseId)), [courses])
  const effectiveSelection = selected.filter((courseId) => selectableCourseIds.has(courseId))
  async function prepare() { setBusy(true); setError(''); try { setPreparation(await prepareExamGeneration(semesterId, effectiveSelection)) } catch (reason) { setError((reason as ExamSchedulingApiError).errors?.map((item) => item.message).join(' ') || 'Could not prepare exams.') } finally { setBusy(false) } }
  async function generate() { if (!preparation) return; setBusy(true); setError(''); try { const value = await generateExams({ semesterId: preparation.semesterId, institutionToday: preparation.institutionToday, sharedSnapshotToken: preparation.sharedSnapshotToken, courses: preparation.courses.map(({ courseId, configurationId, configurationRevision, inputSnapshotToken }) => ({ courseId, configurationId, configurationRevision, inputSnapshotToken })) }); setResult(value); setPreparation(null); setSelected([]); await onChanged(value) } catch (reason) { setError((reason as ExamSchedulingApiError).errors?.map((item) => item.message).join(' ') || 'Could not generate exams. Prepare again.'); setPreparation(null) } finally { setBusy(false) } }
  return <section className="exam-card" aria-labelledby="exam-generation-title"><h3 id="exam-generation-title">Generate exams</h3><p className="constraint-note">Select 1–100 courses. Only explicitly enabled courses without an active exam can be selected.</p><div className="course-picker">{courses.map((course) => { const selectable=selectableCourseIds.has(course.courseId); return <div key={course.courseId}><label className="course-checkbox"><input type="checkbox" checked={effectiveSelection.includes(course.courseId)} disabled={disabled || busy || !selectable} onChange={(event) => setSelected(event.target.checked ? [...effectiveSelection, course.courseId] : effectiveSelection.filter((id) => id !== course.courseId))}/><span>{course.courseName}</span></label>{!course.generationEligibility.eligible && course.generationEligibility.message && <small>{course.generationEligibility.message}</small>}</div>})}</div><p className="selection-count">{effectiveSelection.length} selected</p>{error && <div role="alert" className="alert-item">{error}</div>}{preparation ? <div className="replacement-warning"><p>Review {preparation.courses.length} prepared outcomes. Inputs are protected by snapshot tokens.</p><ul>{preparation.courses.map((course)=><li key={course.courseId}><strong>{course.courseName}</strong>: {course.eligibility.eligible ? 'Ready to generate' : course.eligibility.message ?? course.eligibility.code}</li>)}</ul><div className="dialog-actions"><button type="button" className="secondary-button" disabled={busy} onClick={() => setPreparation(null)}>Cancel</button><button type="button" disabled={busy} onClick={() => void generate()}>{busy ? 'Generating…' : 'Generate confirmed exams'}</button></div></div> : <button type="button" disabled={disabled || busy || effectiveSelection.length < 1 || effectiveSelection.length > 100} onClick={() => void prepare()}>{busy ? 'Preparing…' : 'Prepare exams'}</button>}{result && <ExamGenerationResultSummary result={result}/>}</section>
}
